import 'package:flutter/material.dart';

import '../../data/database/app_database.dart';
import '../../data/models/live_session.dart';
import '../../data/repositories/live_session_repository.dart';

class LiveSessionsPage extends StatefulWidget { const LiveSessionsPage({super.key}); @override State<LiveSessionsPage> createState() => _LiveSessionsPageState(); }
class _LiveSessionsPageState extends State<LiveSessionsPage> {
  final _name = TextEditingController(); final _repository = LiveSessionRepository(AppDatabase.instance); List<LiveSession> _sessions = []; int? _selectedId; DateTime? _startedAt; var _loading = true;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final sessions = await _repository.listSessions(); var selected = await _repository.getSelectedSessionId(); if (selected == null && sessions.isNotEmpty) { selected = sessions.first.id; await _repository.setSelectedSessionId(selected); } if (!mounted) return; setState(() { _sessions = sessions; _selectedId = selected; _loading = false; }); }
  Future<void> _create() async { final text = _name.text.trim(); if (text.isEmpty || _startedAt == null) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Nama Session dan Waktu Mulai wajib diisi.'))); return; } try { final session = await _repository.createSession(name: text, startedAt: _startedAt); if (!mounted) return; _name.clear(); setState(() => _startedAt = null); await _load(); if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('${session.name} dipilih.'))); } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Gagal membuat session.'))); } }
  Future<void> _pickStartedAt() async { final date = await showDatePicker(context: context, firstDate: DateTime(2000), lastDate: DateTime(2100), initialDate: _startedAt ?? DateTime.now()); if (date == null || !mounted) return; final time = await showTimePicker(context: context, initialTime: TimeOfDay.fromDateTime(_startedAt ?? DateTime.now())); if (time != null && mounted) setState(() => _startedAt = DateTime(date.year, date.month, date.day, time.hour, time.minute)); }
  Future<void> _select(int id) async { await _repository.setSelectedSessionId(id); if (mounted) setState(() => _selectedId = id); }
  @override void dispose() { _name.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.all(24), child: _loading ? const Center(child: CircularProgressIndicator()) : Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Live Sessions', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 16), TextField(controller: _name, decoration: const InputDecoration(labelText: 'Nama Session', border: OutlineInputBorder())), const SizedBox(height: 12), ListTile(contentPadding: EdgeInsets.zero, title: const Text('Waktu Mulai'), subtitle: Text(_startedAt?.toLocal().toString() ?? 'Belum dipilih'), trailing: OutlinedButton(onPressed: _pickStartedAt, child: const Text('PILIH'))), Align(alignment: Alignment.centerRight, child: FilledButton(onPressed: _create, child: const Text('BUAT'))), const SizedBox(height: 16), Expanded(child: _sessions.isEmpty ? const Center(child: Text('Belum ada Live Session.')) : ListView.builder(itemCount: _sessions.length, itemBuilder: (context, index) { final session = _sessions[index]; return RadioListTile<int>(value: session.id!, groupValue: _selectedId, onChanged: (value) { if (value != null) _select(value); }, title: Text(session.name), subtitle: Text(session.startedAt?.toLocal().toString() ?? 'Waktu mulai belum diatur'), secondary: session.id == _selectedId ? const Icon(Icons.check_circle) : null); }))]));
}
