import 'package:flutter/material.dart';

import '../../core/currency/rupiah.dart';
import '../../data/database/app_database.dart';
import '../../data/models/live_session.dart';
import '../../data/models/statuses.dart';
import '../../data/models/transaction.dart';
import '../../data/repositories/live_session_repository.dart';
import '../../data/repositories/transaction_repository.dart';
import 'transaction_validator.dart';

class NewSalePage extends StatefulWidget { const NewSalePage({super.key}); @override State<NewSalePage> createState() => _NewSalePageState(); }
class _NewSalePageState extends State<NewSalePage> {
  final _formKey = GlobalKey<FormState>(); final _product = TextEditingController(); final _order = TextEditingController(); final _qty = TextEditingController(); final _gmv = TextEditingController(); final _description = TextEditingController(); final _income = TextEditingController();
  final _sessions = LiveSessionRepository(AppDatabase.instance); final _transactions = TransactionRepository(AppDatabase.instance); List<LiveSession> _availableSessions = []; int? _liveSessionId; var _payment = PaymentStatus.pending; var _orderStatus = OrderStatus.newOrder; DateTime? _paidAt; var _loading = true; var _saving = false;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final sessions = await _sessions.listSessions(); var selected = await _sessions.getSelectedSessionId(); if (!sessions.any((session) => session.id == selected)) selected = sessions.isEmpty ? null : sessions.first.id; if (selected != null) await _sessions.setSelectedSessionId(selected); if (!mounted) return; setState(() { _availableSessions = sessions; _liveSessionId = selected; _loading = false; }); }
  Future<void> _pickPaidDate() async { final selected = await showDatePicker(context: context, firstDate: DateTime(2000), lastDate: DateTime(2100), initialDate: _paidAt ?? DateTime.now()); if (selected != null && mounted) setState(() => _paidAt = selected); }
  Future<void> _submit() async { final gmv = Rupiah.parse(_gmv.text); final income = Rupiah.parse(_income.text); final paidError = TransactionValidator.paidAt(_payment, _paidAt); if (!(_formKey.currentState?.validate() ?? false) || TransactionValidator.rupiah(gmv, 'GMV') != null || TransactionValidator.rupiah(income, 'Penghasilan Bersih') != null || paidError != null) { ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(TransactionValidator.rupiah(gmv, 'GMV') ?? TransactionValidator.rupiah(income, 'Penghasilan Bersih') ?? paidError ?? 'Periksa isian.'))); return; } setState(() => _saving = true); final now = DateTime.now().toUtc(); final transaction = Transaction(liveSessionId: _liveSessionId, productCode: _product.text.trim(), orderId: _order.text.trim(), quantity: int.parse(_qty.text), gmvAmount: gmv!, paymentDescription: _description.text.trim().isEmpty ? null : _description.text.trim(), paymentStatus: _payment, paidAt: TransactionValidator.normalizePaidAt(_payment, _paidAt), netIncomeAmount: income!, orderStatus: _orderStatus, createdAt: now, updatedAt: now); try { await _transactions.insertTransaction(transaction); if (!mounted) return; _product.clear(); _order.clear(); _qty.clear(); _gmv.clear(); _description.clear(); _income.clear(); setState(() { _payment = PaymentStatus.pending; _orderStatus = OrderStatus.newOrder; _paidAt = null; _saving = false; }); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Transaksi berhasil disimpan.'))); } on DuplicateOrderIdException { if (mounted) { setState(() => _saving = false); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('ID Pesanan sudah ada.'))); } } catch (_) { if (mounted) { setState(() => _saving = false); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Gagal menyimpan transaksi.'))); } } }
  @override void dispose() { for (final controller in [_product, _order, _qty, _gmv, _description, _income]) { controller.dispose(); } super.dispose(); }
  @override Widget build(BuildContext context) { if (_loading) return const Center(child: CircularProgressIndicator()); return Form(key: _formKey, child: ListView(padding: const EdgeInsets.all(24), children: [Text('New Sale', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 16), DropdownButtonFormField<int>(value: _liveSessionId, decoration: const InputDecoration(labelText: 'Live Session', border: OutlineInputBorder()), items: _availableSessions.map((s) => DropdownMenuItem(value: s.id, child: Text(s.name))).toList(), onChanged: (value) async { setState(() => _liveSessionId = value); await _sessions.setSelectedSessionId(value); }), _field(_product, 'Kode Barang', TransactionValidator.productCode), _field(_order, 'ID Pesanan', TransactionValidator.orderId), _field(_qty, 'Qty', TransactionValidator.quantity, number: true), _field(_gmv, 'Income / GMV', (value) => TransactionValidator.rupiah(Rupiah.parse(value ?? ''), 'GMV'), number: true), _field(_description, 'Keterangan Pembayaran', null), DropdownButtonFormField<PaymentStatus>(value: _payment, decoration: const InputDecoration(labelText: 'Pembayaran', border: OutlineInputBorder()), items: PaymentStatus.values.map((status) => DropdownMenuItem(value: status, child: Text(status.label))).toList(), onChanged: (value) { if (value == null) return; setState(() { _payment = value; if (value != PaymentStatus.paid) _paidAt = null; }); }), ListTile(contentPadding: EdgeInsets.zero, title: const Text('Tanggal Dibayar'), subtitle: Text(_paidAt == null ? 'Belum dipilih' : '${_paidAt!.day}/${_paidAt!.month}/${_paidAt!.year}'), trailing: OutlinedButton(onPressed: _payment == PaymentStatus.paid ? _pickPaidDate : null, child: const Text('PILIH')),), _field(_income, 'Penghasilan Bersih', (value) => TransactionValidator.rupiah(Rupiah.parse(value ?? ''), 'Penghasilan Bersih'), number: true), DropdownButtonFormField<OrderStatus>(value: _orderStatus, decoration: const InputDecoration(labelText: 'Pesanan', border: OutlineInputBorder()), items: OrderStatus.values.map((status) => DropdownMenuItem(value: status, child: Text(status.label))).toList(), onChanged: (value) { if (value != null) setState(() => _orderStatus = value); }), const SizedBox(height: 20), FilledButton(onPressed: _saving ? null : _submit, child: Text(_saving ? 'MENYIMPAN...' : 'SUBMIT'))])); }
  Widget _field(TextEditingController controller, String label, String? Function(String?)? validator, {bool number = false}) => Padding(padding: const EdgeInsets.only(top: 16), child: TextFormField(controller: controller, validator: validator, keyboardType: number ? TextInputType.number : null, decoration: InputDecoration(labelText: label, border: const OutlineInputBorder())));
}
