import 'package:flutter/material.dart';

import '../../core/currency/rupiah.dart';
import '../../data/database/app_database.dart';
import '../../data/models/live_session.dart';
import '../../data/models/statuses.dart';
import '../../data/models/transaction.dart';
import '../../data/repositories/live_session_repository.dart';
import '../../data/repositories/settings_repository.dart';
import '../../data/repositories/transaction_repository.dart';
import '../sales/transaction_validator.dart';
import 'report_totals.dart';

class ReportsPage extends StatefulWidget { const ReportsPage({super.key}); @override State<ReportsPage> createState() => _ReportsPageState(); }
class _ReportsPageState extends State<ReportsPage> {
  final _search = TextEditingController(); final _transactions = TransactionRepository(AppDatabase.instance); final _settings = SettingsRepository(AppDatabase.instance); final _sessions = LiveSessionRepository(AppDatabase.instance);
  List<Transaction> _items = []; List<LiveSession> _liveSessions = []; int? _sessionId; PaymentStatus? _paymentStatus; OrderStatus? _orderStatus; var _globalHpp = 0; var _loading = true;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final results = await Future.wait([_transactions.listTransactions(search: _search.text, liveSessionId: _sessionId, paymentStatus: _paymentStatus, orderStatus: _orderStatus), _sessions.listSessions(), _settings.getGlobalHpp()]); if (!mounted) return; setState(() { _items = results[0] as List<Transaction>; _liveSessions = results[1] as List<LiveSession>; _globalHpp = results[2] as int? ?? 0; _loading = false; }); }
  void _clearFilters() { setState(() { _search.clear(); _sessionId = null; _paymentStatus = null; _orderStatus = null; }); _load(); }
  Future<void> _edit(Transaction transaction) async { final updated = await showDialog<Transaction>(context: context, builder: (_) => _TransactionEditDialog(transaction: transaction, sessions: _liveSessions)); if (updated == null) return; try { await _transactions.updateTransaction(updated); await _load(); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Transaksi diperbarui.'))); } on DuplicateOrderIdException { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('ID Pesanan sudah ada.'))); } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Gagal memperbarui transaksi.'))); } }
  @override void dispose() { _search.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) { final totals = ReportTotals.fromTransactions(_items, _globalHpp); return Padding(padding: const EdgeInsets.all(24), child: _loading ? const Center(child: CircularProgressIndicator()) : Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Reports', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 16), TextField(controller: _search, onChanged: (_) => _load(), decoration: const InputDecoration(labelText: 'Cari ID Pesanan atau Kode Barang', prefixIcon: Icon(Icons.search), border: OutlineInputBorder())), const SizedBox(height: 12), Wrap(spacing: 12, runSpacing: 12, children: [_filter<int?>('Live Session', _sessionId, [const DropdownMenuItem(value: null, child: Text('SEMUA')), ..._liveSessions.map((session) => DropdownMenuItem(value: session.id, child: Text(session.name)))], (value) { setState(() => _sessionId = value); _load(); }), _filter<PaymentStatus?>('Status Pembayaran', _paymentStatus, [const DropdownMenuItem(value: null, child: Text('SEMUA')), ...PaymentStatus.values.map((status) => DropdownMenuItem(value: status, child: Text(status.label)))], (value) { setState(() => _paymentStatus = value); _load(); }), _filter<OrderStatus?>('Status Pesanan', _orderStatus, [const DropdownMenuItem(value: null, child: Text('SEMUA')), ...OrderStatus.values.map((status) => DropdownMenuItem(value: status, child: Text(status.label)))], (value) { setState(() => _orderStatus = value); _load(); }), OutlinedButton(onPressed: _clearFilters, child: const Text('RESET'))]), const SizedBox(height: 16), _Totals(totals: totals), const SizedBox(height: 16), Expanded(child: _items.isEmpty ? const Center(child: Text('Tidak ada transaksi.')) : SingleChildScrollView(scrollDirection: Axis.horizontal, child: DataTable(columns: const [DataColumn(label: Text('No')), DataColumn(label: Text('Qty')), DataColumn(label: Text('Income / GMV')), DataColumn(label: Text('Kode Barang')), DataColumn(label: Text('ID Pesanan')), DataColumn(label: Text('Keterangan')), DataColumn(label: Text('Dibayar Tanggal')), DataColumn(label: Text('Penghasilan Bersih')), DataColumn(label: Text('HPP')), DataColumn(label: Text('Profit')), DataColumn(label: Text('Status Pembayaran')), DataColumn(label: Text('Status Pesanan')), DataColumn(label: Text('Action'))], rows: [for (var index = 0; index < _items.length; index++) _row(index, _items[index])])))])); }
  DataRow _row(int index, Transaction item) { final hpp = _globalHpp * item.quantity; return DataRow(cells: [DataCell(Text('${index + 1}')), DataCell(Text('${item.quantity}')), DataCell(Text(Rupiah.format(item.gmvAmount))), DataCell(Text(item.productCode)), DataCell(Text(item.orderId)), DataCell(Text(item.paymentDescription ?? '-')), DataCell(Text(item.paidAt == null ? '-' : '${item.paidAt!.day}/${item.paidAt!.month}/${item.paidAt!.year}')), DataCell(Text(Rupiah.format(item.netIncomeAmount))), DataCell(Text(Rupiah.format(hpp))), DataCell(Text(Rupiah.format(item.netIncomeAmount - hpp))), DataCell(Text(item.paymentStatus.label)), DataCell(Text(item.orderStatus.label)), DataCell(TextButton(onPressed: () => _edit(item), child: const Text('Edit')))]); }
  Widget _filter<T>(String label, T value, List<DropdownMenuItem<T>> items, ValueChanged<T?> changed) => SizedBox(width: 220, child: DropdownButtonFormField<T>(initialValue: value, decoration: InputDecoration(labelText: label, border: const OutlineInputBorder()), items: items, onChanged: changed));
}

class _Totals extends StatelessWidget { const _Totals({required this.totals}); final ReportTotals totals; @override Widget build(BuildContext context) => Wrap(spacing: 16, runSpacing: 8, children: [Text('Total GMV: ${Rupiah.format(totals.gmv)}'), Text('Total Penghasilan Bersih: ${Rupiah.format(totals.netIncome)}'), Text('Total HPP: ${Rupiah.format(totals.hpp)}'), Text('Total Profit: ${Rupiah.format(totals.profit)}')]); }

class _TransactionEditDialog extends StatefulWidget { const _TransactionEditDialog({required this.transaction, required this.sessions}); final Transaction transaction; final List<LiveSession> sessions; @override State<_TransactionEditDialog> createState() => _TransactionEditDialogState(); }
class _TransactionEditDialogState extends State<_TransactionEditDialog> {
  final _form = GlobalKey<FormState>(); late final TextEditingController _product; late final TextEditingController _order; late final TextEditingController _qty; late final TextEditingController _gmv; late final TextEditingController _description; late final TextEditingController _income; late int? _sessionId; late PaymentStatus _payment; late OrderStatus _orderStatus; DateTime? _paidAt;
  @override void initState() { super.initState(); final item = widget.transaction; _product = TextEditingController(text: item.productCode); _order = TextEditingController(text: item.orderId); _qty = TextEditingController(text: '${item.quantity}'); _gmv = TextEditingController(text: '${item.gmvAmount}'); _description = TextEditingController(text: item.paymentDescription ?? ''); _income = TextEditingController(text: '${item.netIncomeAmount}'); _sessionId = item.liveSessionId; _payment = item.paymentStatus; _orderStatus = item.orderStatus; _paidAt = item.paidAt; }
  Future<void> _date() async { final value = await showDatePicker(context: context, firstDate: DateTime(2000), lastDate: DateTime(2100), initialDate: _paidAt ?? DateTime.now()); if (value != null && mounted) setState(() => _paidAt = value); }
  void _save() { final gmv = Rupiah.parse(_gmv.text); final income = Rupiah.parse(_income.text); if (!(_form.currentState?.validate() ?? false) || TransactionValidator.rupiah(gmv, 'GMV') != null || TransactionValidator.rupiah(income, 'Penghasilan Bersih') != null || TransactionValidator.paidAt(_payment, _paidAt) != null) return; Navigator.pop(context, widget.transaction.copyWith(liveSessionId: _sessionId, productCode: _product.text.trim(), orderId: _order.text.trim(), quantity: int.parse(_qty.text), gmvAmount: gmv!, paymentDescription: _description.text.trim().isEmpty ? null : _description.text.trim(), paymentStatus: _payment, paidAt: TransactionValidator.normalizePaidAt(_payment, _paidAt), netIncomeAmount: income!, orderStatus: _orderStatus)); }
  @override void dispose() { for (final controller in [_product, _order, _qty, _gmv, _description, _income]) { controller.dispose(); } super.dispose(); }
  @override Widget build(BuildContext context) => AlertDialog(title: const Text('Edit Transaksi'), content: SizedBox(width: 520, child: SingleChildScrollView(child: Form(key: _form, child: Column(mainAxisSize: MainAxisSize.min, children: [DropdownButtonFormField<int>(initialValue: _sessionId, decoration: const InputDecoration(labelText: 'Live Session'), items: widget.sessions.map((item) => DropdownMenuItem(value: item.id, child: Text(item.name))).toList(), onChanged: (value) => setState(() => _sessionId = value)), _field(_product, 'Kode Barang', TransactionValidator.productCode), _field(_order, 'ID Pesanan', TransactionValidator.orderId), _field(_qty, 'Qty', TransactionValidator.quantity), _field(_gmv, 'Income / GMV', (value) => TransactionValidator.rupiah(Rupiah.parse(value ?? ''), 'GMV')), _field(_description, 'Keterangan Pembayaran', null), _control(DropdownButtonFormField<PaymentStatus>(initialValue: _payment, decoration: const InputDecoration(labelText: 'Status Pembayaran'), items: PaymentStatus.values.map((item) => DropdownMenuItem(value: item, child: Text(item.label))).toList(), onChanged: (value) { if (value != null) setState(() { _payment = value; if (value != PaymentStatus.paid) _paidAt = null; }); })), _control(ListTile(contentPadding: EdgeInsets.zero, title: const Text('Tanggal Dibayar'), subtitle: Text(_paidAt == null ? 'Belum dipilih' : '${_paidAt!.day}/${_paidAt!.month}/${_paidAt!.year}'), trailing: OutlinedButton(onPressed: _payment == PaymentStatus.paid ? _date : null, child: const Text('PILIH')))), _field(_income, 'Penghasilan Bersih', (value) => TransactionValidator.rupiah(Rupiah.parse(value ?? ''), 'Penghasilan Bersih')), _control(DropdownButtonFormField<OrderStatus>(initialValue: _orderStatus, decoration: const InputDecoration(labelText: 'Status Pesanan'), items: OrderStatus.values.map((item) => DropdownMenuItem(value: item, child: Text(item.label))).toList(), onChanged: (value) { if (value != null) setState(() => _orderStatus = value); }))])))), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('BATAL')), FilledButton(onPressed: _save, child: const Text('SIMPAN'))]);
  Widget _field(TextEditingController controller, String label, String? Function(String?)? validator) => Padding(padding: const EdgeInsets.only(top: 16), child: TextFormField(controller: controller, validator: validator, decoration: InputDecoration(labelText: label)));
  Widget _control(Widget child) => Padding(padding: const EdgeInsets.only(top: 16), child: child);
}
